services:
  - type: web
    name: findit-app
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://findit-app.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
            name: findit-db
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: laravel
      - key: DB_USERNAME
        value: laravel
      - key: DB_PASSWORD
        fromDatabase:
            name: findit-db

databases:
  - name: findit-db
    plan: free
    databaseName: laravel
    user: laravel
